geometry_msgs/Vector3 rpos

float64 drone_state_x
float64 drone_state_y
float64 drone_state_z

geometry_msgs/Vector3 heading
float32[4] time_encoding

float32 orientation_x
float32 orientation_y
float32 orientation_z
float32 orientation_w

float32 linear_acceleration_x
float32 linear_acceleration_y
float32 linear_acceleration_z

float32 angular_velocity_x
float32 angular_velocity_y
float32 angular_velocity_z

